import 'package:cloud_firestore/cloud_firestore.dart';


class PopulateBooksService {
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  static Future<void> addSampleBooks() async {
    final books = [
      {
        'title': 'Data Structures & Algorithms',
        'author': 'Thomas H. Cormen',
        'swapFor': 'Operating Systems',
        'condition': 'Like New',
        'ownerId': 'sample_user_1',
        'ownerName': 'Alice Johnson',
        'ownerEmail': 'alice@university.edu',
        'status': 'Active',
        'coverImageUrl': 'https://images-na.ssl-images-amazon.com/images/I/41T0iBxY8FL._SX440_BO1,204,203,200_.jpg',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Operating Systems',
        'author': 'John Doe',
        'swapFor': 'Database Systems',
        'condition': 'Used',
        'ownerId': 'sample_user_2',
        'ownerName': 'Bob Smith',
        'ownerEmail': 'bob@university.edu',
        'status': 'Active',
        'coverImageUrl': 'https://images-na.ssl-images-amazon.com/images/I/51xKVEKs7HL._SX389_BO1,204,203,200_.jpg',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Calculus: Early Transcendentals',
        'author': 'James Stewart',
        'swapFor': 'Linear Algebra textbook',
        'condition': 'Good',
        'ownerId': 'sample_user_3',
        'ownerName': 'Carol Davis',
        'ownerEmail': 'carol@university.edu',
        'status': 'Active',
        'coverImageUrl': 'https://images-na.ssl-images-amazon.com/images/I/51H9zKJP8qL._SX389_BO1,204,203,200_.jpg',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Campbell Biology',
        'author': 'Jane B. Reece',
        'swapFor': 'Chemistry textbook',
        'condition': 'Used',
        'ownerId': 'sample_user_4',
        'ownerName': 'David Wilson',
        'ownerEmail': 'david@university.edu',
        'status': 'Active',
        'coverImageUrl': 'https://images-na.ssl-images-amazon.com/images/I/51Kq8eFiOuL._SX389_BO1,204,203,200_.jpg',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Physics for Scientists and Engineers',
        'author': 'Raymond A. Serway',
        'swapFor': 'Engineering textbook',
        'condition': 'New',
        'ownerId': 'sample_user_5',
        'ownerName': 'Emma Brown',
        'ownerEmail': 'emma@university.edu',
        'status': 'Active',
        'coverImageUrl': 'https://images-na.ssl-images-amazon.com/images/I/51xKVEKs7HL._SX389_BO1,204,203,200_.jpg',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Organic Chemistry',
        'author': 'Paula Yurkanis Bruice',
        'swapFor': 'Biochemistry textbook',
        'condition': 'Like New',
        'ownerId': 'sample_user_6',
        'ownerName': 'Frank Miller',
        'ownerEmail': 'frank@university.edu',
        'status': 'Active',
        'coverImageUrl': 'https://images-na.ssl-images-amazon.com/images/I/51rQb-TgzJL._SX389_BO1,204,203,200_.jpg',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Microeconomics',
        'author': 'Robert Pindyck',
        'swapFor': 'Macroeconomics textbook',
        'condition': 'Good',
        'ownerId': 'sample_user_7',
        'ownerName': 'Grace Lee',
        'ownerEmail': 'grace@university.edu',
        'status': 'Active',
        'coverImageUrl': 'https://images-na.ssl-images-amazon.com/images/I/51Kq8eFiOuL._SX389_BO1,204,203,200_.jpg',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Psychology: The Science of Mind and Behaviour',
        'author': 'Michael W. Passer',
        'swapFor': 'Sociology textbook',
        'condition': 'Used',
        'ownerId': 'sample_user_8',
        'ownerName': 'Henry Garcia',
        'ownerEmail': 'henry@university.edu',
        'status': 'Active',
        'coverImageUrl': 'https://images-na.ssl-images-amazon.com/images/I/51xKVEKs7HL._SX389_BO1,204,203,200_.jpg',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Fundamentals of Database Systems',
        'author': 'Ramez Elmasri',
        'swapFor': 'Software Engineering textbook',
        'condition': 'Like New',
        'ownerId': 'sample_user_9',
        'ownerName': 'Ivy Chen',
        'ownerEmail': 'ivy@university.edu',
        'status': 'Active',
        'coverImageUrl': 'https://images-na.ssl-images-amazon.com/images/I/41T0iBxY8FL._SX440_BO1,204,203,200_.jpg',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Computer Networks',
        'author': 'Andrew S. Tanenbaum',
        'swapFor': 'Cybersecurity textbook',
        'condition': 'Good',
        'ownerId': 'sample_user_10',
        'ownerName': 'Jack Taylor',
        'ownerEmail': 'jack@university.edu',
        'status': 'Active',
        'coverImageUrl': 'https://images-na.ssl-images-amazon.com/images/I/51H9zKJP8qL._SX389_BO1,204,203,200_.jpg',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
    ];

    for (var book in books) {
      await _firestore.collection('listings').add(book);
    }
  }
}