import 'package:cloud_firestore/cloud_firestore.dart';
import 'book_cover_service.dart';

class PopulateBooksService {
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  static Future<void> addSampleBooks() async {
    final books = [
      {
        'title': 'Data Structures & Algorithms',
        'author': 'Thomas V. Cormen',
        'swapFor': 'Operating Systems',
        'condition': 'Like New',
        'ownerId': 'sample_user_1',
        'ownerName': 'Alice Johnson',
        'ownerEmail': 'alice@university.edu',
        'status': 'Active',
        'coverImageUrl': BookCoverService.getCoverUrl('Data Structures & Algorithms', 'Thomas V. Cormen'),
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Operating Systems',
        'author': 'John Doe',
        'swapFor': 'Database Systems',
        'condition': 'Used',
        'ownerId': 'sample_user_2',
        'ownerName': 'Bob Smith',
        'ownerEmail': 'bob@university.edu',
        'status': 'Active',
        'coverImageUrl': BookCoverService.getCoverUrl('Operating Systems', 'John Doe'),
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Introduction to Algorithms',
        'author': 'Thomas H. Cormen',
        'swapFor': 'Data Structures textbook',
        'condition': 'Good',
        'ownerId': 'sample_user_3',
        'ownerName': 'Carol Davis',
        'ownerEmail': 'carol@university.edu',
        'status': 'Active',
        'coverImageUrl': BookCoverService.getCoverUrl('Introduction to Algorithms', 'Thomas H. Cormen'),
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'JavaScript: The Definitive Guide',
        'author': 'David Flanagan',
        'swapFor': 'Python Programming',
        'condition': 'Like New',
        'ownerId': 'sample_user_4',
        'ownerName': 'David Wilson',
        'ownerEmail': 'david@university.edu',
        'status': 'Active',
        'coverImageUrl': BookCoverService.getCoverUrl('JavaScript: The Definitive Guide', 'David Flanagan'),
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Clean Code',
        'author': 'Robert C. Martin',
        'swapFor': 'Software Engineering book',
        'condition': 'Good',
        'ownerId': 'sample_user_5',
        'ownerName': 'Emma Brown',
        'ownerEmail': 'emma@university.edu',
        'status': 'Active',
        'coverImageUrl': BookCoverService.getCoverUrl('Clean Code', 'Robert C. Martin'),
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Python Crash Course',
        'author': 'Eric Matthes',
        'swapFor': 'Web Development',
        'condition': 'New',
        'ownerId': 'sample_user_6',
        'ownerName': 'Frank Miller',
        'ownerEmail': 'frank@university.edu',
        'status': 'Active',
        'coverImageUrl': BookCoverService.getCoverUrl('Python Crash Course', 'Eric Matthes'),
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'The Pragmatic Programmer',
        'author': 'David Thomas',
        'swapFor': 'Design Patterns',
        'condition': 'Good',
        'ownerId': 'sample_user_7',
        'ownerName': 'Grace Lee',
        'ownerEmail': 'grace@university.edu',
        'status': 'Active',
        'coverImageUrl': BookCoverService.getCoverUrl('The Pragmatic Programmer', 'David Thomas'),
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Database System Concepts',
        'author': 'Henry F. Korth',
        'swapFor': 'Computer Networks',
        'condition': 'Like New',
        'ownerId': 'sample_user_8',
        'ownerName': 'Henry Garcia',
        'ownerEmail': 'henry@university.edu',
        'status': 'Active',
        'coverImageUrl': BookCoverService.getCoverUrl('Database System Concepts', 'Henry F. Korth'),
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Introduction to Statistical Learning',
        'author': 'Gareth James',
        'swapFor': 'Machine Learning',
        'condition': 'Good',
        'ownerId': 'sample_user_9',
        'ownerName': 'Ivy Chen',
        'ownerEmail': 'ivy@university.edu',
        'status': 'Active',
        'coverImageUrl': BookCoverService.getCoverUrl('Introduction to Statistical Learning', 'Gareth James'),
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Computer Networks',
        'author': 'Andrew S. Tanenbaum',
        'swapFor': 'Cybersecurity',
        'condition': 'Used',
        'ownerId': 'sample_user_10',
        'ownerName': 'Jack Taylor',
        'ownerEmail': 'jack@university.edu',
        'status': 'Active',
        'coverImageUrl': BookCoverService.getCoverUrl('Computer Networks', 'Andrew S. Tanenbaum'),
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
    ];

    for (var book in books) {
      await _firestore.collection('listings').add(book);
    }
  }
}