import 'package:cloud_firestore/cloud_firestore.dart';

class PopulateBooksService {
  static final FirebaseFirestore _firestore = FirebaseFirestore.instance;

  static Future<void> addSampleBooks() async {
    final books = [
      {
        'title': 'Introduction to Algorithms',
        'author': 'Thomas H. Cormen',
        'swapFor': 'Data Structures textbook',
        'condition': 'Good',
        'ownerId': 'sample_user_1',
        'ownerName': 'Sample User',
        'ownerEmail': 'sample@example.com',
        'status': 'Active',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Clean Code',
        'author': 'Robert C. Martin',
        'swapFor': 'Software Engineering book',
        'condition': 'Like New',
        'ownerId': 'sample_user_2',
        'ownerName': 'John Doe',
        'ownerEmail': 'john@example.com',
        'status': 'Active',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Design Patterns',
        'author': 'Gang of Four',
        'swapFor': 'Architecture book',
        'condition': 'Good',
        'ownerId': 'sample_user_3',
        'ownerName': 'Jane Smith',
        'ownerEmail': 'jane@example.com',
        'status': 'Active',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Calculus: Early Transcendentals',
        'author': 'James Stewart',
        'swapFor': 'Linear Algebra book',
        'condition': 'Used',
        'ownerId': 'sample_user_4',
        'ownerName': 'Mike Johnson',
        'ownerEmail': 'mike@example.com',
        'status': 'Active',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Operating System Concepts',
        'author': 'Abraham Silberschatz',
        'swapFor': 'Computer Networks book',
        'condition': 'Good',
        'ownerId': 'sample_user_5',
        'ownerName': 'Sarah Wilson',
        'ownerEmail': 'sarah@example.com',
        'status': 'Active',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Database System Concepts',
        'author': 'Henry F. Korth',
        'swapFor': 'Web Development book',
        'condition': 'Like New',
        'ownerId': 'sample_user_6',
        'ownerName': 'David Brown',
        'ownerEmail': 'david@example.com',
        'status': 'Active',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Computer Networks',
        'author': 'Andrew S. Tanenbaum',
        'swapFor': 'Security textbook',
        'condition': 'Good',
        'ownerId': 'sample_user_7',
        'ownerName': 'Lisa Davis',
        'ownerEmail': 'lisa@example.com',
        'status': 'Active',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Artificial Intelligence',
        'author': 'Stuart Russell',
        'swapFor': 'Machine Learning book',
        'condition': 'New',
        'ownerId': 'sample_user_8',
        'ownerName': 'Tom Anderson',
        'ownerEmail': 'tom@example.com',
        'status': 'Active',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Linear Algebra and Its Applications',
        'author': 'David C. Lay',
        'swapFor': 'Statistics book',
        'condition': 'Good',
        'ownerId': 'sample_user_9',
        'ownerName': 'Emma Taylor',
        'ownerEmail': 'emma@example.com',
        'status': 'Active',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
      {
        'title': 'Discrete Mathematics',
        'author': 'Kenneth H. Rosen',
        'swapFor': 'Probability book',
        'condition': 'Like New',
        'ownerId': 'sample_user_10',
        'ownerName': 'Chris Lee',
        'ownerEmail': 'chris@example.com',
        'status': 'Active',
        'createdAt': FieldValue.serverTimestamp(),
        'updatedAt': FieldValue.serverTimestamp(),
      },
    ];

    for (var book in books) {
      await _firestore.collection('listings').add(book);
    }
  }
}