// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdoWw3C5alXg7dqBPZAUwbO5X6iPsQNVw',
    appId: '1:786574117177:web:e2c6a730f6c648255a00e8',
    messagingSenderId: '786574117177',
    projectId: 'bookswap-4b750',
    authDomain: 'bookswap-4b750.firebaseapp.com',
    storageBucket: 'bookswap-4b750.firebasestorage.app',
    measurementId: 'G-6G1MQEVSCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdoWw3C5alXg7dqBPZAUwbO5X6iPsQNVw',
    appId: '1:786574117177:android:e2c6a730f6c648255a00e8',
    messagingSenderId: '786574117177',
    projectId: 'bookswap-4b750',
    storageBucket: 'bookswap-4b750.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdoWw3C5alXg7dqBPZAUwbO5X6iPsQNVw',
    appId: '1:786574117177:ios:e2c6a730f6c648255a00e8',
    messagingSenderId: '786574117177',
    projectId: 'bookswap-4b750',
    storageBucket: 'bookswap-4b750.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdoWw3C5alXg7dqBPZAUwbO5X6iPsQNVw',
    appId: '1:786574117177:macos:e2c6a730f6c648255a00e8',
    messagingSenderId: '786574117177',
    projectId: 'bookswap-4b750',
    storageBucket: 'bookswap-4b750.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdoWw3C5alXg7dqBPZAUwbO5X6iPsQNVw',
    appId: '1:786574117177:web:e2c6a730f6c648255a00e8',
    messagingSenderId: '786574117177',
    projectId: 'bookswap-4b750',
    authDomain: 'bookswap-4b750.firebaseapp.com',
    storageBucket: 'bookswap-4b750.firebasestorage.app',
    measurementId: 'G-6G1MQEVSCM',
  );
}